# Generated by Django 6.0 on 2025-12-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='annual_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose_of_loan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
