"""
Django settings for lms_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

_env_loaded = False
_env_dir = BASE_DIR
for _ in range(8):
    _candidate = _env_dir / ".env"
    if _candidate.is_file():
        # Prefer real environment (Render, etc.); .env only fills missing keys
        load_dotenv(_candidate, override=False)
        _env_loaded = True
        break
    if _env_dir.parent == _env_dir:
        break
    _env_dir = _env_dir.parent
if not _env_loaded:
    load_dotenv(override=False)

SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret")

DEBUG = os.getenv("DEBUG", "False") == "True"

_allowed_raw = os.getenv("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in _allowed_raw.split(",") if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]
# Render may assign a unique hostname (e.g. service-name-abc1.onrender.com)
if (
    os.environ.get("RENDER", "").lower() == "true"
    and "*" not in ALLOWED_HOSTS
    and ".onrender.com" not in ALLOWED_HOSTS
):
    ALLOWED_HOSTS.append(".onrender.com")

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'loans',
]

CSRF_TRUSTED_ORIGINS = [
    "https://fintech-lms-backend.onrender.com",
    "https://fintech-lms-backend-e7q7.onrender.com",
    "https://fintech-lms-frontend.onrender.com",
]

# CORS settings - Allow frontend to access backend
CORS_ALLOWED_ORIGINS = [
    "https://fintech-lms-frontend.onrender.com",
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'lms_backend.urls'

CORS_ALLOW_ALL_ORIGINS = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lms_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_url = os.getenv("DATABASE_URL")
if database_url:
    # Production: Use PostgreSQL from DATABASE_URL
    # Hosted Render URLs use postgresql://...render.com — require SSL (old check missed postgresql://)
    _db_url = database_url
    _on_render = os.environ.get("RENDER", "").lower() == "true"
    # Free / serverless dynos: persistent connections often go stale → use 0 on Render
    _conn_max_age = 0 if _on_render else 600
    # SSL: required for *.render.com external host; internal dpg-* hostnames often fail if ssl forced
    _ssl = "render.com" in _db_url
    if os.getenv("DATABASE_SSL_REQUIRE", "").lower() in ("1", "true", "yes"):
        _ssl = True
    if os.getenv("DATABASE_SSL_REQUIRE", "").lower() in ("0", "false", "no"):
        _ssl = False
    _db_cfg = dj_database_url.parse(
        _db_url,
        conn_max_age=_conn_max_age,
        ssl_require=_ssl,
    )
    # Re-verify connection per request (helps free dynos + dropped PG connections)
    _db_cfg["CONN_HEALTH_CHECKS"] = True
    if not _db_cfg.get("OPTIONS"):
        _db_cfg["OPTIONS"] = {}
    _db_cfg["OPTIONS"].setdefault("connect_timeout", 10)
    DATABASES = {"default": _db_cfg}
else:
    # Local development: Fallback to SQLite. Use SQLITE_DB_PATH to store the DB outside OneDrive/sync
    # folders if you see `unable to open database file` on Windows (Path must be writable).
    _sqlite_override = os.getenv("SQLITE_DB_PATH")
    _sqlite_name = (
        Path(_sqlite_override).expanduser()
        if _sqlite_override
        else (BASE_DIR / "db.sqlite3")
    )
    _sqlite_name = _sqlite_name.resolve()
    _sqlite_name.parent.mkdir(parents=True, exist_ok=True)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(_sqlite_name),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Manifest storage 500s if staticfiles.json and disk disagree; plain compressed is safer on PaaS
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# REST Framework + SimpleJWT configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # No session auth → browser POSTs from the SPA do not hit CSRF checks (session auth is on by default).
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

# On Render/production, avoid BrowsableAPIRenderer (HTML) — it can 500 if templates/static edge cases.
if os.environ.get("RENDER", "").lower() == "true" or not DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
    ]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}
